/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as DemoDecouvrirIndexRouteImport } from './routes/demo/decouvrir/index'
import { Route as DemoCabinetVeterinaireDesPignesIndexRouteImport } from './routes/demo/cabinet-veterinaire-des-pignes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDecouvrirIndexRoute = DemoDecouvrirIndexRouteImport.update({
  id: '/demo/decouvrir/',
  path: '/demo/decouvrir/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCabinetVeterinaireDesPignesIndexRoute =
  DemoCabinetVeterinaireDesPignesIndexRouteImport.update({
    id: '/demo/cabinet-veterinaire-des-pignes/',
    path: '/demo/cabinet-veterinaire-des-pignes/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fr/': typeof FrIndexRoute
  '/demo/cabinet-veterinaire-des-pignes/': typeof DemoCabinetVeterinaireDesPignesIndexRoute
  '/demo/decouvrir/': typeof DemoDecouvrirIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fr': typeof FrIndexRoute
  '/demo/cabinet-veterinaire-des-pignes': typeof DemoCabinetVeterinaireDesPignesIndexRoute
  '/demo/decouvrir': typeof DemoDecouvrirIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fr/': typeof FrIndexRoute
  '/demo/cabinet-veterinaire-des-pignes/': typeof DemoCabinetVeterinaireDesPignesIndexRoute
  '/demo/decouvrir/': typeof DemoDecouvrirIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/fr/' | '/demo/cabinet-veterinaire-des-pignes/' | '/demo/decouvrir/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fr' | '/demo/cabinet-veterinaire-des-pignes' | '/demo/decouvrir'
  id:
    | '__root__'
    | '/'
    | '/fr/'
    | '/demo/cabinet-veterinaire-des-pignes/'
    | '/demo/decouvrir/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrIndexRoute: typeof FrIndexRoute
  DemoCabinetVeterinaireDesPignesIndexRoute: typeof DemoCabinetVeterinaireDesPignesIndexRoute
  DemoDecouvrirIndexRoute: typeof DemoDecouvrirIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/decouvrir/': {
      id: '/demo/decouvrir/'
      path: '/demo/decouvrir'
      fullPath: '/demo/decouvrir/'
      preLoaderRoute: typeof DemoDecouvrirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/cabinet-veterinaire-des-pignes/': {
      id: '/demo/cabinet-veterinaire-des-pignes/'
      path: '/demo/cabinet-veterinaire-des-pignes'
      fullPath: '/demo/cabinet-veterinaire-des-pignes/'
      preLoaderRoute: typeof DemoCabinetVeterinaireDesPignesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrIndexRoute: FrIndexRoute,
  DemoCabinetVeterinaireDesPignesIndexRoute:
    DemoCabinetVeterinaireDesPignesIndexRoute,
  DemoDecouvrirIndexRoute: DemoDecouvrirIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
