/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as DemoMaisonFIndexRouteImport } from './routes/demo/maison-f/index'
import { Route as DemoLesSensIndexRouteImport } from './routes/demo/les-sens/index'
import { Route as DemoLePanierIndexRouteImport } from './routes/demo/le-panier/index'
import { Route as DemoLaReserveIndexRouteImport } from './routes/demo/la-reserve/index'
import { Route as DemoExempleIndexRouteImport } from './routes/demo/exemple/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMaisonFIndexRoute = DemoMaisonFIndexRouteImport.update({
  id: '/demo/maison-f/',
  path: '/demo/maison-f/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLesSensIndexRoute = DemoLesSensIndexRouteImport.update({
  id: '/demo/les-sens/',
  path: '/demo/les-sens/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLePanierIndexRoute = DemoLePanierIndexRouteImport.update({
  id: '/demo/le-panier/',
  path: '/demo/le-panier/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLaReserveIndexRoute = DemoLaReserveIndexRouteImport.update({
  id: '/demo/la-reserve/',
  path: '/demo/la-reserve/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoExempleIndexRoute = DemoExempleIndexRouteImport.update({
  id: '/demo/exemple/',
  path: '/demo/exemple/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fr/': typeof FrIndexRoute
  '/demo/exemple/': typeof DemoExempleIndexRoute
  '/demo/la-reserve/': typeof DemoLaReserveIndexRoute
  '/demo/le-panier/': typeof DemoLePanierIndexRoute
  '/demo/les-sens/': typeof DemoLesSensIndexRoute
  '/demo/maison-f/': typeof DemoMaisonFIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fr': typeof FrIndexRoute
  '/demo/exemple': typeof DemoExempleIndexRoute
  '/demo/la-reserve': typeof DemoLaReserveIndexRoute
  '/demo/le-panier': typeof DemoLePanierIndexRoute
  '/demo/les-sens': typeof DemoLesSensIndexRoute
  '/demo/maison-f': typeof DemoMaisonFIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fr/': typeof FrIndexRoute
  '/demo/exemple/': typeof DemoExempleIndexRoute
  '/demo/la-reserve/': typeof DemoLaReserveIndexRoute
  '/demo/le-panier/': typeof DemoLePanierIndexRoute
  '/demo/les-sens/': typeof DemoLesSensIndexRoute
  '/demo/maison-f/': typeof DemoMaisonFIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fr/'
    | '/demo/exemple/'
    | '/demo/la-reserve/'
    | '/demo/le-panier/'
    | '/demo/les-sens/'
    | '/demo/maison-f/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fr'
    | '/demo/exemple'
    | '/demo/la-reserve'
    | '/demo/le-panier'
    | '/demo/les-sens'
    | '/demo/maison-f'
  id:
    | '__root__'
    | '/'
    | '/fr/'
    | '/demo/exemple/'
    | '/demo/la-reserve/'
    | '/demo/le-panier/'
    | '/demo/les-sens/'
    | '/demo/maison-f/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrIndexRoute: typeof FrIndexRoute
  DemoExempleIndexRoute: typeof DemoExempleIndexRoute
  DemoLaReserveIndexRoute: typeof DemoLaReserveIndexRoute
  DemoLePanierIndexRoute: typeof DemoLePanierIndexRoute
  DemoLesSensIndexRoute: typeof DemoLesSensIndexRoute
  DemoMaisonFIndexRoute: typeof DemoMaisonFIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/maison-f/': {
      id: '/demo/maison-f/'
      path: '/demo/maison-f'
      fullPath: '/demo/maison-f/'
      preLoaderRoute: typeof DemoMaisonFIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/les-sens/': {
      id: '/demo/les-sens/'
      path: '/demo/les-sens'
      fullPath: '/demo/les-sens/'
      preLoaderRoute: typeof DemoLesSensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/le-panier/': {
      id: '/demo/le-panier/'
      path: '/demo/le-panier'
      fullPath: '/demo/le-panier/'
      preLoaderRoute: typeof DemoLePanierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/la-reserve/': {
      id: '/demo/la-reserve/'
      path: '/demo/la-reserve'
      fullPath: '/demo/la-reserve/'
      preLoaderRoute: typeof DemoLaReserveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/exemple/': {
      id: '/demo/exemple/'
      path: '/demo/exemple'
      fullPath: '/demo/exemple/'
      preLoaderRoute: typeof DemoExempleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrIndexRoute: FrIndexRoute,
  DemoExempleIndexRoute: DemoExempleIndexRoute,
  DemoLaReserveIndexRoute: DemoLaReserveIndexRoute,
  DemoLePanierIndexRoute: DemoLePanierIndexRoute,
  DemoLesSensIndexRoute: DemoLesSensIndexRoute,
  DemoMaisonFIndexRoute: DemoMaisonFIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
